const productsData = [
  {
    "id": 1,
    "name": "Dark Chocolate Truffle",
    "category": "Cakes",
    "subCategory": "Chocolate",
    "price": 50,
    "image": "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=600&q=80",
    "rating": "4.6",
    "reviews": 431,
    "isBestseller": false,
    "flavor": "Chocolate"
  },
  {
    "id": 2,
    "name": "Choco Lava Delight",
    "category": "Cakes",
    "subCategory": "Chocolate",
    "price": 57,
    "image": "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=600&q=80",
    "rating": "4.9",
    "reviews": 392,
    "isBestseller": false,
    "flavor": "Chocolate"
  },
  {
    "id": 3,
    "name": "German Chocolate",
    "category": "Cakes",
    "subCategory": "Chocolate",
    "price": 49,
    "image": "https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=600&q=80",
    "rating": "3.9",
    "reviews": 203,
    "isBestseller": false,
    "flavor": "Chocolate"
  },
  {
    "id": 4,
    "name": "Triple Chocolate Mousse",
    "category": "Cakes",
    "subCategory": "Chocolate",
    "price": 41,
    "image": "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=600&q=80",
    "rating": "5.0",
    "reviews": 92,
    "isBestseller": true,
    "flavor": "Chocolate"
  },
  {
    "id": 5,
    "name": "Choco Hazelnut",
    "category": "Cakes",
    "subCategory": "Chocolate",
    "price": 36,
    "image": "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=600&q=80",
    "rating": "4.1",
    "reviews": 33,
    "isBestseller": false,
    "flavor": "Chocolate"
  },
  {
    "id": 6,
    "name": "Death by Chocolate",
    "category": "Cakes",
    "subCategory": "Chocolate",
    "price": 42,
    "image": "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=600&q=80",
    "rating": "3.5",
    "reviews": 446,
    "isBestseller": true,
    "flavor": "Chocolate"
  },
  {
    "id": 7,
    "name": "Ferrero Rocher Cake",
    "category": "Cakes",
    "subCategory": "Chocolate",
    "price": 51,
    "image": "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=600&q=80",
    "rating": "4.3",
    "reviews": 98,
    "isBestseller": true,
    "flavor": "Chocolate"
  },
  {
    "id": 8,
    "name": "Mocha Fudge",
    "category": "Cakes",
    "subCategory": "Chocolate",
    "price": 56,
    "image": "https://images.unsplash.com/photo-1519869325930-281384150729?auto=format&fit=crop&w=600&q=80",
    "rating": "4.0",
    "reviews": 508,
    "isBestseller": false,
    "flavor": "Chocolate"
  },
  {
    "id": 9,
    "name": "Belgian Chocolate",
    "category": "Cakes",
    "subCategory": "Chocolate",
    "price": 42,
    "image": "https://images.unsplash.com/photo-1587668178277-295251f900ce?auto=format&fit=crop&w=600&q=80",
    "rating": "3.6",
    "reviews": 397,
    "isBestseller": false,
    "flavor": "Chocolate"
  },
  {
    "id": 10,
    "name": "Choco Chip Layer",
    "category": "Cakes",
    "subCategory": "Chocolate",
    "price": 31,
    "image": "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=600&q=80",
    "rating": "4.3",
    "reviews": 284,
    "isBestseller": false,
    "flavor": "Chocolate"
  },
  {
    "id": 11,
    "name": "Fresh Pineapple",
    "category": "Cakes",
    "subCategory": "Fruit",
    "price": 49,
    "image": "https://images.unsplash.com/photo-1585478259715-876a6a81fa08?auto=format&fit=crop&w=600&q=80",
    "rating": "4.9",
    "reviews": 405,
    "isBestseller": false,
    "flavor": "Fruit"
  },
  {
    "id": 12,
    "name": "Mixed Berry Blast",
    "category": "Cakes",
    "subCategory": "Fruit",
    "price": 41,
    "image": "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=600&q=80",
    "rating": "4.2",
    "reviews": 337,
    "isBestseller": false,
    "flavor": "Fruit"
  },
  {
    "id": 13,
    "name": "Mango Tango",
    "category": "Cakes",
    "subCategory": "Fruit",
    "price": 44,
    "image": "https://images.unsplash.com/photo-1602664773289-e13cbdae2023?auto=format&fit=crop&w=600&q=80",
    "rating": "4.9",
    "reviews": 261,
    "isBestseller": false,
    "flavor": "Fruit"
  },
  {
    "id": 14,
    "name": "Strawberry Shortcake",
    "category": "Cakes",
    "subCategory": "Fruit",
    "price": 42,
    "image": "https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=600&q=80",
    "rating": "4.7",
    "reviews": 388,
    "isBestseller": false,
    "flavor": "Fruit"
  },
  {
    "id": 15,
    "name": "Blueberry Cream",
    "category": "Cakes",
    "subCategory": "Fruit",
    "price": 40,
    "image": "https://images.unsplash.com/photo-1587668178277-295251f900ce?auto=format&fit=crop&w=600&q=80",
    "rating": "3.9",
    "reviews": 97,
    "isBestseller": true,
    "flavor": "Fruit"
  },
  {
    "id": 16,
    "name": "Zesty Lemon",
    "category": "Cakes",
    "subCategory": "Fruit",
    "price": 38,
    "image": "https://images.unsplash.com/photo-1588195538320-062002235bd1?auto=format&fit=crop&w=600&q=80",
    "rating": "4.3",
    "reviews": 401,
    "isBestseller": false,
    "flavor": "Fruit"
  },
  {
    "id": 17,
    "name": "Kiwi Sensation",
    "category": "Cakes",
    "subCategory": "Fruit",
    "price": 49,
    "image": "https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?auto=format&fit=crop&w=600&q=80",
    "rating": "4.7",
    "reviews": 393,
    "isBestseller": false,
    "flavor": "Fruit"
  },
  {
    "id": 18,
    "name": "Tropical Fruit",
    "category": "Cakes",
    "subCategory": "Fruit",
    "price": 47,
    "image": "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=600&q=80",
    "rating": "3.8",
    "reviews": 11,
    "isBestseller": true,
    "flavor": "Fruit"
  },
  {
    "id": 19,
    "name": "Unicorn Fantasy",
    "category": "Cakes",
    "subCategory": "Designer",
    "price": 62,
    "image": "https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?auto=format&fit=crop&w=600&q=80",
    "rating": "3.9",
    "reviews": 157,
    "isBestseller": false,
    "flavor": "Designer"
  },
  {
    "id": 20,
    "name": "Mermaid Tail",
    "category": "Cakes",
    "subCategory": "Designer",
    "price": 57,
    "image": "https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?auto=format&fit=crop&w=600&q=80",
    "rating": "4.1",
    "reviews": 68,
    "isBestseller": true,
    "flavor": "Designer"
  },
  {
    "id": 21,
    "name": "Galaxy Drip",
    "category": "Cakes",
    "subCategory": "Designer",
    "price": 65,
    "image": "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=600&q=80",
    "rating": "4.3",
    "reviews": 67,
    "isBestseller": false,
    "flavor": "Designer"
  },
  {
    "id": 22,
    "name": "Fondant Floral",
    "category": "Cakes",
    "subCategory": "Designer",
    "price": 74,
    "image": "https://images.unsplash.com/photo-1519869325930-281384150729?auto=format&fit=crop&w=600&q=80",
    "rating": "4.5",
    "reviews": 112,
    "isBestseller": false,
    "flavor": "Designer"
  },
  {
    "id": 23,
    "name": "Super Hero Theme",
    "category": "Cakes",
    "subCategory": "Designer",
    "price": 90,
    "image": "https://images.unsplash.com/photo-1587668178277-295251f900ce?auto=format&fit=crop&w=600&q=80",
    "rating": "3.8",
    "reviews": 210,
    "isBestseller": false,
    "flavor": "Designer"
  },
  {
    "id": 24,
    "name": "Princess Castle",
    "category": "Cakes",
    "subCategory": "Designer",
    "price": 81,
    "image": "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=600&q=80",
    "rating": "4.1",
    "reviews": 220,
    "isBestseller": false,
    "flavor": "Designer"
  },
  {
    "id": 25,
    "name": "Gold Leaf Elegant",
    "category": "Cakes",
    "subCategory": "Designer",
    "price": 95,
    "image": "https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=600&q=80",
    "rating": "4.8",
    "reviews": 135,
    "isBestseller": false,
    "flavor": "Designer"
  },
  {
    "id": 26,
    "name": "Classic Tiered White",
    "category": "Cakes",
    "subCategory": "Wedding",
    "price": 252,
    "image": "https://images.unsplash.com/photo-1555507036-ab1f40ce88cb?auto=format&fit=crop&w=600&q=80",
    "rating": "5.0",
    "reviews": 53,
    "isBestseller": false,
    "flavor": "Wedding"
  },
  {
    "id": 27,
    "name": "Rustic Naked Cake",
    "category": "Cakes",
    "subCategory": "Wedding",
    "price": 217,
    "image": "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=600&q=80",
    "rating": "4.9",
    "reviews": 191,
    "isBestseller": false,
    "flavor": "Wedding"
  },
  {
    "id": 28,
    "name": "Rose Gold Romance",
    "category": "Cakes",
    "subCategory": "Wedding",
    "price": 154,
    "image": "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=600&q=80",
    "rating": "4.5",
    "reviews": 240,
    "isBestseller": false,
    "flavor": "Wedding"
  },
  {
    "id": 29,
    "name": "Vintage Lace",
    "category": "Cakes",
    "subCategory": "Wedding",
    "price": 101,
    "image": "https://images.unsplash.com/photo-1519869325930-281384150729?auto=format&fit=crop&w=600&q=80",
    "rating": "4.7",
    "reviews": 87,
    "isBestseller": false,
    "flavor": "Wedding"
  },
  {
    "id": 30,
    "name": "Pearl Adorned",
    "category": "Cakes",
    "subCategory": "Wedding",
    "price": 247,
    "image": "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=600&q=80",
    "rating": "4.3",
    "reviews": 425,
    "isBestseller": false,
    "flavor": "Wedding"
  },
  {
    "id": 31,
    "name": "Classic Vanilla Bean",
    "category": "Cupcakes",
    "subCategory": "Vanilla",
    "price": 4,
    "image": "https://images.unsplash.com/photo-1614707267537-b85aaf00c4b7?auto=format&fit=crop&w=600&q=80",
    "rating": "3.9",
    "reviews": 233,
    "isBestseller": false,
    "flavor": "Vanilla"
  },
  {
    "id": 32,
    "name": "Vanilla Sprinkles",
    "category": "Cupcakes",
    "subCategory": "Vanilla",
    "price": 3,
    "image": "https://images.unsplash.com/photo-1602664773289-e13cbdae2023?auto=format&fit=crop&w=600&q=80",
    "rating": "4.3",
    "reviews": 447,
    "isBestseller": true,
    "flavor": "Vanilla"
  },
  {
    "id": 33,
    "name": "Golden Vanilla",
    "category": "Cupcakes",
    "subCategory": "Vanilla",
    "price": 5,
    "image": "https://images.unsplash.com/photo-1614707267537-b85aaf00c4b7?auto=format&fit=crop&w=600&q=80",
    "rating": "4.4",
    "reviews": 316,
    "isBestseller": true,
    "flavor": "Vanilla"
  },
  {
    "id": 34,
    "name": "Vanilla Raspberry",
    "category": "Cupcakes",
    "subCategory": "Vanilla",
    "price": 4,
    "image": "https://images.unsplash.com/photo-1555507036-ab1f40ce88cb?auto=format&fit=crop&w=600&q=80",
    "rating": "4.0",
    "reviews": 48,
    "isBestseller": false,
    "flavor": "Vanilla"
  },
  {
    "id": 35,
    "name": "Vanilla Caramel",
    "category": "Cupcakes",
    "subCategory": "Vanilla",
    "price": 5,
    "image": "https://images.unsplash.com/photo-1585478259715-876a6a81fa08?auto=format&fit=crop&w=600&q=80",
    "rating": "4.0",
    "reviews": 22,
    "isBestseller": false,
    "flavor": "Vanilla"
  },
  {
    "id": 36,
    "name": "Double Chocolate",
    "category": "Cupcakes",
    "subCategory": "Chocolate",
    "price": 7,
    "image": "https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?auto=format&fit=crop&w=600&q=80",
    "rating": "4.6",
    "reviews": 121,
    "isBestseller": false,
    "flavor": "Chocolate"
  },
  {
    "id": 37,
    "name": "Choco Mint",
    "category": "Cupcakes",
    "subCategory": "Chocolate",
    "price": 7,
    "image": "https://images.unsplash.com/photo-1550617931-e17a7b70dce2?auto=format&fit=crop&w=600&q=80",
    "rating": "4.1",
    "reviews": 136,
    "isBestseller": false,
    "flavor": "Chocolate"
  },
  {
    "id": 38,
    "name": "Choco Peanut Butter",
    "category": "Cupcakes",
    "subCategory": "Chocolate",
    "price": 7,
    "image": "https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=600&q=80",
    "rating": "4.3",
    "reviews": 497,
    "isBestseller": true,
    "flavor": "Chocolate"
  },
  {
    "id": 39,
    "name": "Choco Cherry",
    "category": "Cupcakes",
    "subCategory": "Chocolate",
    "price": 5,
    "image": "https://images.unsplash.com/photo-1551106651-1abf33c6fac0?auto=format&fit=crop&w=600&q=80",
    "rating": "4.0",
    "reviews": 478,
    "isBestseller": false,
    "flavor": "Chocolate"
  },
  {
    "id": 40,
    "name": "Dark Choco Ganache",
    "category": "Cupcakes",
    "subCategory": "Chocolate",
    "price": 7,
    "image": "https://images.unsplash.com/photo-1550617931-e17a7b70dce2?auto=format&fit=crop&w=600&q=80",
    "rating": "4.4",
    "reviews": 68,
    "isBestseller": false,
    "flavor": "Chocolate"
  },
  {
    "id": 41,
    "name": "Classic Red Velvet",
    "category": "Cupcakes",
    "subCategory": "Red Velvet",
    "price": 6,
    "image": "https://images.unsplash.com/photo-1550617931-e17a7b70dce2?auto=format&fit=crop&w=600&q=80",
    "rating": "4.1",
    "reviews": 155,
    "isBestseller": false,
    "flavor": "Red Velvet"
  },
  {
    "id": 42,
    "name": "Red Velvet Cream Cheese",
    "category": "Cupcakes",
    "subCategory": "Red Velvet",
    "price": 7,
    "image": "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=600&q=80",
    "rating": "3.9",
    "reviews": 60,
    "isBestseller": false,
    "flavor": "Red Velvet"
  },
  {
    "id": 43,
    "name": "Red Velvet Berry",
    "category": "Cupcakes",
    "subCategory": "Red Velvet",
    "price": 5,
    "image": "https://images.unsplash.com/photo-1602664773289-e13cbdae2023?auto=format&fit=crop&w=600&q=80",
    "rating": "4.2",
    "reviews": 84,
    "isBestseller": true,
    "flavor": "Red Velvet"
  },
  {
    "id": 44,
    "name": "Mini Red Velvet",
    "category": "Cupcakes",
    "subCategory": "Red Velvet",
    "price": 4,
    "image": "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=600&q=80",
    "rating": "4.5",
    "reviews": 310,
    "isBestseller": false,
    "flavor": "Red Velvet"
  },
  {
    "id": 45,
    "name": "Classic Red Velvet 2",
    "category": "Cupcakes",
    "subCategory": "Red Velvet",
    "price": 4,
    "image": "https://images.unsplash.com/photo-1614707267537-b85aaf00c4b7?auto=format&fit=crop&w=600&q=80",
    "rating": "4.3",
    "reviews": 254,
    "isBestseller": false,
    "flavor": "Red Velvet"
  },
  {
    "id": 46,
    "name": "Oreo Dream",
    "category": "Cupcakes",
    "subCategory": "Specialty",
    "price": 6,
    "image": "https://images.unsplash.com/photo-1555507036-ab1f40ce88cb?auto=format&fit=crop&w=600&q=80",
    "rating": "4.5",
    "reviews": 312,
    "isBestseller": false,
    "flavor": "Specialty"
  },
  {
    "id": 47,
    "name": "Salted Caramel",
    "category": "Cupcakes",
    "subCategory": "Specialty",
    "price": 5,
    "image": "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=600&q=80",
    "rating": "3.7",
    "reviews": 436,
    "isBestseller": true,
    "flavor": "Specialty"
  },
  {
    "id": 48,
    "name": "Lemon Meringue",
    "category": "Cupcakes",
    "subCategory": "Specialty",
    "price": 5,
    "image": "https://images.unsplash.com/photo-1587668178277-295251f900ce?auto=format&fit=crop&w=600&q=80",
    "rating": "4.3",
    "reviews": 294,
    "isBestseller": false,
    "flavor": "Specialty"
  },
  {
    "id": 49,
    "name": "Matcha Green Tea",
    "category": "Cupcakes",
    "subCategory": "Specialty",
    "price": 5,
    "image": "https://images.unsplash.com/photo-1621303837174-89787a7d4729?auto=format&fit=crop&w=600&q=80",
    "rating": "4.1",
    "reviews": 16,
    "isBestseller": false,
    "flavor": "Specialty"
  },
  {
    "id": 50,
    "name": "Coffee Mocha",
    "category": "Cupcakes",
    "subCategory": "Specialty",
    "price": 6,
    "image": "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=600&q=80",
    "rating": "4.6",
    "reviews": 94,
    "isBestseller": false,
    "flavor": "Specialty"
  },
  {
    "id": 51,
    "name": "Butter Cookies",
    "category": "Cookies",
    "subCategory": "Classic",
    "price": 5,
    "image": "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=600&q=80",
    "rating": "3.7",
    "reviews": 348,
    "isBestseller": false,
    "flavor": "Classic"
  },
  {
    "id": 52,
    "name": "Choco Chip",
    "category": "Cookies",
    "subCategory": "Classic",
    "price": 4,
    "image": "https://images.unsplash.com/photo-1585478259715-876a6a81fa08?auto=format&fit=crop&w=600&q=80",
    "rating": "4.7",
    "reviews": 259,
    "isBestseller": false,
    "flavor": "Classic"
  },
  {
    "id": 53,
    "name": "Oatmeal Raisin",
    "category": "Cookies",
    "subCategory": "Classic",
    "price": 2,
    "image": "https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?auto=format&fit=crop&w=600&q=80",
    "rating": "4.8",
    "reviews": 486,
    "isBestseller": true,
    "flavor": "Classic"
  },
  {
    "id": 54,
    "name": "Peanut Butter",
    "category": "Cookies",
    "subCategory": "Classic",
    "price": 5,
    "image": "https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=600&q=80",
    "rating": "4.9",
    "reviews": 30,
    "isBestseller": false,
    "flavor": "Classic"
  },
  {
    "id": 55,
    "name": "Snickerdoodle",
    "category": "Cookies",
    "subCategory": "Classic",
    "price": 4,
    "image": "https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=600&q=80",
    "rating": "5.0",
    "reviews": 44,
    "isBestseller": false,
    "flavor": "Classic"
  },
  {
    "id": 56,
    "name": "White Choco Macadamia",
    "category": "Cookies",
    "subCategory": "Premium",
    "price": 7,
    "image": "https://images.unsplash.com/photo-1621303837174-89787a7d4729?auto=format&fit=crop&w=600&q=80",
    "rating": "4.3",
    "reviews": 372,
    "isBestseller": true,
    "flavor": "Premium"
  },
  {
    "id": 57,
    "name": "Double Choco Chunk",
    "category": "Cookies",
    "subCategory": "Premium",
    "price": 5,
    "image": "https://images.unsplash.com/photo-1587668178277-295251f900ce?auto=format&fit=crop&w=600&q=80",
    "rating": "4.1",
    "reviews": 118,
    "isBestseller": false,
    "flavor": "Premium"
  },
  {
    "id": 58,
    "name": "Almond Biscotti",
    "category": "Cookies",
    "subCategory": "Premium",
    "price": 6,
    "image": "https://images.unsplash.com/photo-1588195538320-062002235bd1?auto=format&fit=crop&w=600&q=80",
    "rating": "5.0",
    "reviews": 100,
    "isBestseller": true,
    "flavor": "Premium"
  },
  {
    "id": 59,
    "name": "Pistachio Cranberry",
    "category": "Cookies",
    "subCategory": "Premium",
    "price": 4,
    "image": "https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?auto=format&fit=crop&w=600&q=80",
    "rating": "4.6",
    "reviews": 366,
    "isBestseller": true,
    "flavor": "Premium"
  },
  {
    "id": 60,
    "name": "White Choco Macadamia 2",
    "category": "Cookies",
    "subCategory": "Premium",
    "price": 6,
    "image": "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=600&q=80",
    "rating": "3.9",
    "reviews": 64,
    "isBestseller": false,
    "flavor": "Premium"
  },
  {
    "id": 61,
    "name": "French Vanilla Macaron",
    "category": "Cookies",
    "subCategory": "Macarons",
    "price": 17,
    "image": "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=600&q=80",
    "rating": "4.8",
    "reviews": 108,
    "isBestseller": false,
    "flavor": "Macarons"
  },
  {
    "id": 62,
    "name": "Pistachio Macaron",
    "category": "Cookies",
    "subCategory": "Macarons",
    "price": 14,
    "image": "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=600&q=80",
    "rating": "3.7",
    "reviews": 259,
    "isBestseller": false,
    "flavor": "Macarons"
  },
  {
    "id": 63,
    "name": "Raspberry Macaron",
    "category": "Cookies",
    "subCategory": "Macarons",
    "price": 12,
    "image": "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=600&q=80",
    "rating": "3.7",
    "reviews": 416,
    "isBestseller": false,
    "flavor": "Macarons"
  },
  {
    "id": 64,
    "name": "Lavender Macaron",
    "category": "Cookies",
    "subCategory": "Macarons",
    "price": 17,
    "image": "https://images.unsplash.com/photo-1585478259715-876a6a81fa08?auto=format&fit=crop&w=600&q=80",
    "rating": "4.9",
    "reviews": 210,
    "isBestseller": false,
    "flavor": "Macarons"
  },
  {
    "id": 65,
    "name": "Lemon Macaron",
    "category": "Cookies",
    "subCategory": "Macarons",
    "price": 11,
    "image": "https://images.unsplash.com/photo-1585478259715-876a6a81fa08?auto=format&fit=crop&w=600&q=80",
    "rating": "4.7",
    "reviews": 26,
    "isBestseller": false,
    "flavor": "Macarons"
  },
  {
    "id": 66,
    "name": "Original Glazed",
    "category": "Donuts",
    "subCategory": "Classic",
    "price": 4,
    "image": "https://images.unsplash.com/photo-1550617931-e17a7b70dce2?auto=format&fit=crop&w=600&q=80",
    "rating": "4.0",
    "reviews": 418,
    "isBestseller": false,
    "flavor": "Classic"
  },
  {
    "id": 67,
    "name": "Chocolate Frosted",
    "category": "Donuts",
    "subCategory": "Classic",
    "price": 3,
    "image": "https://images.unsplash.com/photo-1587668178277-295251f900ce?auto=format&fit=crop&w=600&q=80",
    "rating": "4.7",
    "reviews": 464,
    "isBestseller": false,
    "flavor": "Classic"
  },
  {
    "id": 68,
    "name": "Strawberry Sprinkles",
    "category": "Donuts",
    "subCategory": "Classic",
    "price": 4,
    "image": "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=600&q=80",
    "rating": "4.6",
    "reviews": 413,
    "isBestseller": true,
    "flavor": "Classic"
  },
  {
    "id": 69,
    "name": "Cinnamon Sugar",
    "category": "Donuts",
    "subCategory": "Classic",
    "price": 2,
    "image": "https://images.unsplash.com/photo-1519869325930-281384150729?auto=format&fit=crop&w=600&q=80",
    "rating": "4.6",
    "reviews": 369,
    "isBestseller": false,
    "flavor": "Classic"
  },
  {
    "id": 70,
    "name": "Original Glazed 2",
    "category": "Donuts",
    "subCategory": "Classic",
    "price": 2,
    "image": "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=600&q=80",
    "rating": "4.8",
    "reviews": 373,
    "isBestseller": true,
    "flavor": "Classic"
  },
  {
    "id": 71,
    "name": "Nutella Filled",
    "category": "Donuts",
    "subCategory": "Filled",
    "price": 4,
    "image": "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=600&q=80",
    "rating": "3.8",
    "reviews": 47,
    "isBestseller": true,
    "flavor": "Filled"
  },
  {
    "id": 72,
    "name": "Boston Cream",
    "category": "Donuts",
    "subCategory": "Filled",
    "price": 6,
    "image": "https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=600&q=80",
    "rating": "4.1",
    "reviews": 381,
    "isBestseller": false,
    "flavor": "Filled"
  },
  {
    "id": 73,
    "name": "Jelly Filled",
    "category": "Donuts",
    "subCategory": "Filled",
    "price": 6,
    "image": "https://images.unsplash.com/photo-1569864358642-9d1684040f43?auto=format&fit=crop&w=600&q=80",
    "rating": "4.6",
    "reviews": 82,
    "isBestseller": true,
    "flavor": "Filled"
  },
  {
    "id": 74,
    "name": "Vanilla Custard",
    "category": "Donuts",
    "subCategory": "Filled",
    "price": 3,
    "image": "https://images.unsplash.com/photo-1551106651-1abf33c6fac0?auto=format&fit=crop&w=600&q=80",
    "rating": "4.1",
    "reviews": 346,
    "isBestseller": false,
    "flavor": "Filled"
  },
  {
    "id": 75,
    "name": "Nutella Filled 2",
    "category": "Donuts",
    "subCategory": "Filled",
    "price": 3,
    "image": "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=600&q=80",
    "rating": "4.9",
    "reviews": 347,
    "isBestseller": false,
    "flavor": "Filled"
  },
  {
    "id": 76,
    "name": "Maple Bacon",
    "category": "Donuts",
    "subCategory": "Gourmet",
    "price": 5,
    "image": "https://images.unsplash.com/photo-1555507036-ab1f40ce88cb?auto=format&fit=crop&w=600&q=80",
    "rating": "4.1",
    "reviews": 59,
    "isBestseller": false,
    "flavor": "Gourmet"
  },
  {
    "id": 77,
    "name": "Matcha Glazed",
    "category": "Donuts",
    "subCategory": "Gourmet",
    "price": 4,
    "image": "https://images.unsplash.com/photo-1621303837174-89787a7d4729?auto=format&fit=crop&w=600&q=80",
    "rating": "4.4",
    "reviews": 65,
    "isBestseller": true,
    "flavor": "Gourmet"
  },
  {
    "id": 78,
    "name": "Caramel Crunch",
    "category": "Donuts",
    "subCategory": "Gourmet",
    "price": 7,
    "image": "https://images.unsplash.com/photo-1569864358642-9d1684040f43?auto=format&fit=crop&w=600&q=80",
    "rating": "3.9",
    "reviews": 245,
    "isBestseller": false,
    "flavor": "Gourmet"
  },
  {
    "id": 79,
    "name": "Blueberry Crumble",
    "category": "Donuts",
    "subCategory": "Gourmet",
    "price": 7,
    "image": "https://images.unsplash.com/photo-1550617931-e17a7b70dce2?auto=format&fit=crop&w=600&q=80",
    "rating": "3.5",
    "reviews": 367,
    "isBestseller": false,
    "flavor": "Gourmet"
  },
  {
    "id": 80,
    "name": "Smores Donut",
    "category": "Donuts",
    "subCategory": "Gourmet",
    "price": 7,
    "image": "https://images.unsplash.com/photo-1585478259715-876a6a81fa08?auto=format&fit=crop&w=600&q=80",
    "rating": "4.3",
    "reviews": 100,
    "isBestseller": false,
    "flavor": "Gourmet"
  },
  {
    "id": 81,
    "name": "Ultimate Birthday Box",
    "category": "Gift Hampers",
    "subCategory": "Birthday",
    "price": 56,
    "image": "https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=600&q=80",
    "rating": "4.9",
    "reviews": 187,
    "isBestseller": false,
    "flavor": "Birthday"
  },
  {
    "id": 82,
    "name": "Sweet Sixteen Hamper",
    "category": "Gift Hampers",
    "subCategory": "Birthday",
    "price": 76,
    "image": "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=600&q=80",
    "rating": "3.7",
    "reviews": 392,
    "isBestseller": false,
    "flavor": "Birthday"
  },
  {
    "id": 83,
    "name": "Kids Party Pack",
    "category": "Gift Hampers",
    "subCategory": "Birthday",
    "price": 45,
    "image": "https://images.unsplash.com/photo-1555507036-ab1f40ce88cb?auto=format&fit=crop&w=600&q=80",
    "rating": "4.2",
    "reviews": 424,
    "isBestseller": false,
    "flavor": "Birthday"
  },
  {
    "id": 84,
    "name": "Choco Lover Birthday",
    "category": "Gift Hampers",
    "subCategory": "Birthday",
    "price": 52,
    "image": "https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=600&q=80",
    "rating": "4.7",
    "reviews": 304,
    "isBestseller": false,
    "flavor": "Birthday"
  },
  {
    "id": 85,
    "name": "Surprise Mini Cakes",
    "category": "Gift Hampers",
    "subCategory": "Birthday",
    "price": 66,
    "image": "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=600&q=80",
    "rating": "4.4",
    "reviews": 497,
    "isBestseller": false,
    "flavor": "Birthday"
  },
  {
    "id": 86,
    "name": "Romantic Rose Hamper",
    "category": "Gift Hampers",
    "subCategory": "Anniversary",
    "price": 74,
    "image": "https://images.unsplash.com/photo-1602664773289-e13cbdae2023?auto=format&fit=crop&w=600&q=80",
    "rating": "4.6",
    "reviews": 233,
    "isBestseller": false,
    "flavor": "Anniversary"
  },
  {
    "id": 87,
    "name": "Silver Jubilee Treat",
    "category": "Gift Hampers",
    "subCategory": "Anniversary",
    "price": 98,
    "image": "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=600&q=80",
    "rating": "4.6",
    "reviews": 427,
    "isBestseller": false,
    "flavor": "Anniversary"
  },
  {
    "id": 88,
    "name": "Golden Anniversary Special",
    "category": "Gift Hampers",
    "subCategory": "Anniversary",
    "price": 86,
    "image": "https://images.unsplash.com/photo-1555507036-ab1f40ce88cb?auto=format&fit=crop&w=600&q=80",
    "rating": "3.8",
    "reviews": 433,
    "isBestseller": true,
    "flavor": "Anniversary"
  },
  {
    "id": 89,
    "name": "Love & Chocolates",
    "category": "Gift Hampers",
    "subCategory": "Anniversary",
    "price": 87,
    "image": "https://images.unsplash.com/photo-1585478259715-876a6a81fa08?auto=format&fit=crop&w=600&q=80",
    "rating": "4.4",
    "reviews": 369,
    "isBestseller": false,
    "flavor": "Anniversary"
  },
  {
    "id": 90,
    "name": "Couples Dessert Box",
    "category": "Gift Hampers",
    "subCategory": "Anniversary",
    "price": 73,
    "image": "https://images.unsplash.com/photo-1602664773289-e13cbdae2023?auto=format&fit=crop&w=600&q=80",
    "rating": "3.8",
    "reviews": 399,
    "isBestseller": false,
    "flavor": "Anniversary"
  },
  {
    "id": 91,
    "name": "Executive Treat Box",
    "category": "Gift Hampers",
    "subCategory": "Corporate",
    "price": 70,
    "image": "https://images.unsplash.com/photo-1519869325930-281384150729?auto=format&fit=crop&w=600&q=80",
    "rating": "4.1",
    "reviews": 165,
    "isBestseller": false,
    "flavor": "Corporate"
  },
  {
    "id": 92,
    "name": "Office Celebration",
    "category": "Gift Hampers",
    "subCategory": "Corporate",
    "price": 136,
    "image": "https://images.unsplash.com/photo-1602664773289-e13cbdae2023?auto=format&fit=crop&w=600&q=80",
    "rating": "4.9",
    "reviews": 59,
    "isBestseller": false,
    "flavor": "Corporate"
  },
  {
    "id": 93,
    "name": "Client Appreciation",
    "category": "Gift Hampers",
    "subCategory": "Corporate",
    "price": 92,
    "image": "https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=600&q=80",
    "rating": "4.0",
    "reviews": 422,
    "isBestseller": false,
    "flavor": "Corporate"
  },
  {
    "id": 94,
    "name": "Team Success Hamper",
    "category": "Gift Hampers",
    "subCategory": "Corporate",
    "price": 69,
    "image": "https://images.unsplash.com/photo-1614707267537-b85aaf00c4b7?auto=format&fit=crop&w=600&q=80",
    "rating": "3.7",
    "reviews": 168,
    "isBestseller": false,
    "flavor": "Corporate"
  },
  {
    "id": 95,
    "name": "Premium Desk Snacks",
    "category": "Gift Hampers",
    "subCategory": "Corporate",
    "price": 132,
    "image": "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=600&q=80",
    "rating": "4.5",
    "reviews": 71,
    "isBestseller": false,
    "flavor": "Corporate"
  },
  {
    "id": 96,
    "name": "Diwali Sweet Box",
    "category": "Gift Hampers",
    "subCategory": "Festival",
    "price": 54,
    "image": "https://images.unsplash.com/photo-1519869325930-281384150729?auto=format&fit=crop&w=600&q=80",
    "rating": "3.6",
    "reviews": 359,
    "isBestseller": true,
    "flavor": "Festival"
  },
  {
    "id": 97,
    "name": "Christmas Joy Hamper",
    "category": "Gift Hampers",
    "subCategory": "Festival",
    "price": 64,
    "image": "https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=600&q=80",
    "rating": "4.9",
    "reviews": 39,
    "isBestseller": false,
    "flavor": "Festival"
  },
  {
    "id": 98,
    "name": "Holi Special Treats",
    "category": "Gift Hampers",
    "subCategory": "Festival",
    "price": 52,
    "image": "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=600&q=80",
    "rating": "3.5",
    "reviews": 163,
    "isBestseller": true,
    "flavor": "Festival"
  },
  {
    "id": 99,
    "name": "Eid Dessert Platter",
    "category": "Gift Hampers",
    "subCategory": "Festival",
    "price": 35,
    "image": "https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=600&q=80",
    "rating": "3.7",
    "reviews": 86,
    "isBestseller": false,
    "flavor": "Festival"
  },
  {
    "id": 100,
    "name": "Festive Celebration",
    "category": "Gift Hampers",
    "subCategory": "Festival",
    "price": 81,
    "image": "https://images.unsplash.com/photo-1614707267537-b85aaf00c4b7?auto=format&fit=crop&w=600&q=80",
    "rating": "3.5",
    "reviews": 79,
    "isBestseller": false,
    "flavor": "Festival"
  }
];